name: Close All Pull Requests

on:
  pull_request:
    types:
      #- labeled
      #- unlabeled
      #- synchronize
      - opened
      #- edited
      #- ready_for_review
      #- reopened
jobs:
  comment:
    if: contains(github.event.comment.body, '')

    runs-on: ubuntu-latest

    steps:
      - name: Add comment to PR
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           echo $URL
           echo $repository
           echo $comment-id
