name: Close All Pull Requests

on:
  pull_request:
    types:
      #- labeled
      #- unlabeled
      #- synchronize
      - opened
      #- edited
      #- ready_for_review
      #- reopened
jobs:
  comment:
    if: contains(github.event.comment.body, '')

    runs-on: ubuntu-latest

    steps:
      - name: Add comment to PR
        env:
          URL: ${{ github.event.issue.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "bala"
